# 1. http port
quarkus.http.port=${PORT:8080}
quarkus.http.host=0.0.0.0

#2 time out
quarkus.http.read-timeout=30m
quarkus.http.idle-timeout=30m




# 2. 배포를 쉽게 하기 위해 'Uber-Jar' 모드로 빌드 설정
quarkus.package.type=uber-jar

# Jib 컨테이너 이미지 설정
quarkus.container-image.build=true
quarkus.container-image.push=true
quarkus.container-image.image=asia-northeast3-docker.pkg.dev/every-shift-api/containers/hello-world-job:v1

# --- Application Configuration ---
# Default mode is API. Set to JOB for Cloud Run Job execution.
app.mode=${APP_MODE:API}
# If true, runs the solver logic locally via WorkerResource (Async) instead of Cloud Tasks.
app.solver.run-locally=true

# --- Google Cloud Configuration ---

# ??? ???? ?? IP?? ?? ???? ?? (WSL2 ??? ??)
quarkus.live-reload.debug-host=0.0.0.0

# H2? ??? DB? ?? (?? ???)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb


gcp.project-id=every-shift-api
gcp.location-id=asia-northeast3
gcp.queue-id=solver-queue
gcp.worker-url=https://every-shift-api-service-x3l5zfq7ya-du.a.run.app/worker/process
gcp.service-account-email=every-shift-solver-invoker@every-shift-api.iam.gserviceaccount.com


# --- OptaPlanner Configuration ---
quarkus.optaplanner.constraint-provider=org.acme.solver.algorithm.ShiftConstraintProvider

# --- Solver Custom Configuration ---
# Default / Prod
solver.termination.spent-limit=60
solver.termination.unimproved-spent-limit=10
solver.termination.best-score-feasible=false
solver.termination.best-score-limit=0hard/0soft
solver.move-thread-count=4
solver.environment-mode=REPRODUCIBLE
solver.random-seed=42

# Dev profile
%dev.solver.termination.spent-limit=10
%dev.solver.termination.unimproved-spent-limit=5

# Test profile
%test.solver.termination.spent-limit=2
%test.solver.termination.unimproved-spent-limit=1